apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-volume
spec:
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteMany # Allows multiple pods to access the volume
  hostPath:
    path: /data/shared
